/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.18).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.AuthResponse;
import io.swagger.model.AuthenticationData;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-02-27T15:59:20.699Z[GMT]")
@Api(value = "autenticazione", description = "the autenticazione API")
public interface AutenticazioneApi {

    @ApiOperation(value = "", nickname = "autenticazioneLoginPost", notes = "", response = AuthResponse.class, tags={ "userAuthentication", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = AuthResponse.class),
        @ApiResponse(code = 400, message = "incorrect credentials") })
    @RequestMapping(value = "/autenticazione/login",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<AuthResponse> autenticazioneLoginPost(@ApiParam(value = ""  )  @Valid @RequestBody AuthenticationData body
);

}
