/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.18).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.PlaceAuthenticatedMovement;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-02-27T15:59:20.699Z[GMT]")
@Api(value = "AuthenticatedPlaceAcces", description = "the AuthenticatedPlaceAcces API")
public interface AuthenticatedPlaceAccesApi {

    @ApiOperation(value = "the administrator can retieve all the access made in every place of his organization", nickname = "getAuthenticatedPlaceAccess", notes = "get all the access in every place in the specified organization", response = PlaceAuthenticatedMovement.class, responseContainer = "List", tags={ "place", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = PlaceAuthenticatedMovement.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "Invalid Id supplied"),
        @ApiResponse(code = 404, message = "Access not found") })
    @RequestMapping(value = "/AuthenticatedPlaceAcces/{organizationId}",
        produces = { "application/json", "application/xml" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<PlaceAuthenticatedMovement>> getAuthenticatedPlaceAccess(@ApiParam(value = "ID of an organization",required=true) @PathVariable("organizationId") Long organizationId
);

}
