/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.2.3).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.qbteam.api;

import it.qbteam.model.OrganizationAccess;
import it.qbteam.model.PlaceAccess;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.constraints.*;
import java.util.List;

@Validated
@Api(value = "access", description = "the access API")
public interface AccessApi {

    /**
     * GET /access/organization/{organizationId}/authenticated/{orgAuthServerIds} : Returns all the authenticated accesses in an organization registered of one or more users (orgAuthServerIds are separated by commas).
     * Returns all the authenticated accesses in an organization registered of one or more users (orgAuthServerIds are separated by commas) that are fully registered. Fully registered means that there are both the entrance and the exit timestamp. Both app users and web-app admininistrators can access this end-point.
     *
     * @param orgAuthServerIds One or more orgAuthServerIds. If it is called by the app user, the orgAuthServerIds parameter can only consist in one identifier. Otherwise it can be more than one identifier. (required)
     * @param organizationId ID of an organization (required)
     * @return List of authenticated accesses in an organization gets returned successfully. (status code 200)
     *         or List of authenticated accesses in an organization were not found. Nothing gets returned. (status code 204)
     *         or The administrator or the user is not authenticated. Nothing gets returned. (status code 401)
     *         or The organization could not be found. Nothing gets returned. (status code 404)
     */
    @ApiOperation(value = "Returns all the authenticated accesses in an organization registered of one or more users (orgAuthServerIds are separated by commas).", nickname = "getAuthenticatedAccessListInOrganization", notes = "Returns all the authenticated accesses in an organization registered of one or more users (orgAuthServerIds are separated by commas) that are fully registered. Fully registered means that there are both the entrance and the exit timestamp. Both app users and web-app admininistrators can access this end-point.", response = OrganizationAccess.class, responseContainer = "List", authorizations = {
        @Authorization(value = "bearerAuth")
    }, tags={ "access","organization", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "List of authenticated accesses in an organization gets returned successfully.", response = OrganizationAccess.class, responseContainer = "List"),
        @ApiResponse(code = 204, message = "List of authenticated accesses in an organization were not found. Nothing gets returned."),
        @ApiResponse(code = 401, message = "The administrator or the user is not authenticated. Nothing gets returned."),
        @ApiResponse(code = 404, message = "The organization could not be found. Nothing gets returned.") })
    @RequestMapping(value = "/access/organization/{organizationId}/authenticated/{orgAuthServerIds}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<OrganizationAccess>> getAuthenticatedAccessListInOrganization(@ApiParam(value = "One or more orgAuthServerIds. If it is called by the app user, the orgAuthServerIds parameter can only consist in one identifier. Otherwise it can be more than one identifier.",required=true) @PathVariable("orgAuthServerIds") List<String> orgAuthServerIds,@Min(1L)@ApiParam(value = "ID of an organization",required=true) @PathVariable("organizationId") Long organizationId);


    /**
     * GET /access/place/{placeId}/authenticated/{orgAuthServerIds} : Returns all the authenticated accesses in a place registered of one or more users (orgAuthServerIds are separated by commas).
     * Returns all the authenticated accesses in a place registered of one or more users (orgAuthServerIds are separated by commas) that are fully registered. Fully registered means that there are both the entrance and the exit timestamp. Both app users and web-app admininistrators can access this end-point.
     *
     * @param orgAuthServerIds One or more orgAuthServerIds. If it is called by the app user, the orgAuthServerIds parameter can only consist in one identifier. Otherwise it can be more than one identifier. (required)
     * @param placeId ID of a place. (required)
     * @return List of authenticated accesses in a place gets returned successfully. (status code 200)
     *         or List of authenticated accesses in a place were not found. Nothing gets returned. (status code 204)
     *         or The administrator or the user is not authenticated. Nothing gets returned. (status code 401)
     *         or The place could not be found. Nothing gets returned. (status code 404)
     */
    @ApiOperation(value = "Returns all the authenticated accesses in a place registered of one or more users (orgAuthServerIds are separated by commas).", nickname = "getAuthenticatedAccessListInPlace", notes = "Returns all the authenticated accesses in a place registered of one or more users (orgAuthServerIds are separated by commas) that are fully registered. Fully registered means that there are both the entrance and the exit timestamp. Both app users and web-app admininistrators can access this end-point.", response = PlaceAccess.class, responseContainer = "List", authorizations = {
        @Authorization(value = "bearerAuth")
    }, tags={ "access","place", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "List of authenticated accesses in a place gets returned successfully.", response = PlaceAccess.class, responseContainer = "List"),
        @ApiResponse(code = 204, message = "List of authenticated accesses in a place were not found. Nothing gets returned."),
        @ApiResponse(code = 401, message = "The administrator or the user is not authenticated. Nothing gets returned."),
        @ApiResponse(code = 404, message = "The place could not be found. Nothing gets returned.") })
    @RequestMapping(value = "/access/place/{placeId}/authenticated/{orgAuthServerIds}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<PlaceAccess>> getAuthenticatedAccessListInPlace(@ApiParam(value = "One or more orgAuthServerIds. If it is called by the app user, the orgAuthServerIds parameter can only consist in one identifier. Otherwise it can be more than one identifier.",required=true) @PathVariable("orgAuthServerIds") List<String> orgAuthServerIds,@Min(1L)@ApiParam(value = "ID of a place.",required=true) @PathVariable("placeId") Long placeId);

}
