/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.2.3).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.qbteam.api;

import it.qbteam.model.OrganizationMovement;
import it.qbteam.model.PlaceMovement;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;

@Validated
@Api(value = "movement", description = "the movement API")
public interface MovementApi {

    /**
     * POST /movement/track/organization : Tracks the user movement inside the trackingArea of an organization.
     * Tracks the user movement inside the trackingArea of an organization.
     *
     * @param organizationMovement  (required)
     * @return Entrance movement successfully tracked. The movement with the exitToken gets returned. (status code 201)
     *         or Exit movement successfully tracked. Nothing gets returned. (status code 202)
     *         or Exit movement was requested without the exitToken. It will not be tracked. Nothing gets returned. (status code 400)
     *         or The user is not authenticated. Nothing gets returned. (status code 401)
     *         or Administrators cannot have access. Nothing gets returned. (status code 403)
     */
    @ApiOperation(value = "Tracks the user movement inside the trackingArea of an organization.", nickname = "trackMovementInOrganization", notes = "Tracks the user movement inside the trackingArea of an organization.", response = OrganizationMovement.class, authorizations = {
        @Authorization(value = "bearerAuth")
    }, tags={ "movement","organization", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Entrance movement successfully tracked. The movement with the exitToken gets returned.", response = OrganizationMovement.class),
        @ApiResponse(code = 202, message = "Exit movement successfully tracked. Nothing gets returned."),
        @ApiResponse(code = 400, message = "Exit movement was requested without the exitToken. It will not be tracked. Nothing gets returned."),
        @ApiResponse(code = 401, message = "The user is not authenticated. Nothing gets returned."),
        @ApiResponse(code = 403, message = "Administrators cannot have access. Nothing gets returned.") })
    @RequestMapping(value = "/movement/track/organization",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<OrganizationMovement> trackMovementInOrganization(@ApiParam(value = "" ,required=true )  @Valid @RequestBody OrganizationMovement organizationMovement);


    /**
     * POST /movement/track/place : Tracks the user movement inside the trackingArea of a place of an organization.
     * Tracks the user movement inside the trackingArea of a place of an organization.
     *
     * @param placeMovement  (required)
     * @return Entrance movement successfully tracked. The movement with the exitToken gets returned. (status code 201)
     *         or Exit movement successfully tracked. Nothing gets returned. (status code 202)
     *         or Exit movement was requested without the exitToken. It will not be tracked. Nothing gets returned. (status code 400)
     *         or The user is not authenticated. Nothing gets returned. (status code 401)
     *         or Administrators cannot have access. Nothing gets returned. (status code 403)
     */
    @ApiOperation(value = "Tracks the user movement inside the trackingArea of a place of an organization.", nickname = "trackMovementInPlace", notes = "Tracks the user movement inside the trackingArea of a place of an organization.", response = PlaceMovement.class, authorizations = {
        @Authorization(value = "bearerAuth")
    }, tags={ "movement","place", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Entrance movement successfully tracked. The movement with the exitToken gets returned.", response = PlaceMovement.class),
        @ApiResponse(code = 202, message = "Exit movement successfully tracked. Nothing gets returned."),
        @ApiResponse(code = 400, message = "Exit movement was requested without the exitToken. It will not be tracked. Nothing gets returned."),
        @ApiResponse(code = 401, message = "The user is not authenticated. Nothing gets returned."),
        @ApiResponse(code = 403, message = "Administrators cannot have access. Nothing gets returned.") })
    @RequestMapping(value = "/movement/track/place",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<PlaceMovement> trackMovementInPlace(@ApiParam(value = "" ,required=true )  @Valid @RequestBody PlaceMovement placeMovement);

}
