SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

CREATE DATABASE IF NOT EXISTS `stalker` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `stalker`;

CREATE TABLE `Favorite` (
  `userId` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Authentication service''s user unique identifier.',
  `organizationId` bigint NOT NULL COMMENT 'Unique identifier of the organization the user sets as favorite.',
  `orgAuthId` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'User unique identifier from the authentication server of the organization.',
  `creationDate` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'When the favorite was added by the user.'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Link between the user and the organization: only the organization which users set to be their favorite can track their movements.';

CREATE TABLE `Organization` (
  `id` bigint NOT NULL COMMENT 'Unique identifier for an organization.',
  `name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Name of the organization.',
  `description` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Small description of what the organization does.',
  `image` varchar(300) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Image/logo for the organization which gets shown on the application.',
  `street` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'The street where the organization is located.',
  `number` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'The number in the street where the organization is located.',
  `postCode` int UNSIGNED DEFAULT NULL COMMENT 'The postcode where the organization is located.',
  `city` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'The city where the organization is located.',
  `country` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'The country where the organization is located.',
  `authenticationServerURL` varchar(2048) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'URL or IP address of the authentication server of the organization. If it''s required a specific port or protocol it must be specified. Needed only if trackingMethod is set to authenticated.',
  `creationDate` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'When the organization was added to the system.',
  `lastChangeDate` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'When the organization parameters were last changed.',
  `trackingArea` json NOT NULL COMMENT 'Area subjected to movement tracking of people. It is a collection of (longitude, latitude) pairs consisting in a polygon. The string is expressed in JSON format.',
  `trackingMode` enum('authenticated','anonymous') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'How an user who added to its favorites the organization can be tracked inside the organization''s trackingArea and its places.'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Subject interested in tracking people&#39;s presence inside its own places, in either an anonymous or authenticated way.';

CREATE TABLE `OrganizationAccess` (
  `id` bigint NOT NULL,
  `entranceTimestamp` datetime NOT NULL COMMENT 'Date and time of the moment in which the user entered the place.',
  `exitTimestamp` datetime DEFAULT NULL COMMENT 'Date and time of the moment in which the user left the place.',
  `exitToken` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Token generated by the server required for registering the user exit movement.',
  `organizationId` bigint NOT NULL COMMENT 'Unique identifier of the organization in which the user had access.',
  `orgAuthServerId` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'User unique identifier from the authentication server of the organization.'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Access to an organization.';

CREATE TABLE `Permission` (
  `administratorId` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Authentication service''s administrator unique identifier.',
  `organizationId` bigint NOT NULL COMMENT 'Unique identifier of the organization the administrator is part of.',
  `orgAuthServerId` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Administrator unique identifier from the authentication server of the organization.',
  `permission` tinyint UNSIGNED NOT NULL COMMENT 'What can or cannot do an organization''s administrator. The permission levels are: - Owner: 3 (higher level) - Manager: 2 - Viewer: 1 (lowest level)',
  `nominatedBy` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'administratorId of the owner administrator who nominated the current administrator.'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='What can or cannot do an organization&#39;s administrator.';

CREATE TABLE `Place` (
  `id` bigint NOT NULL COMMENT 'Unique identifier for a place of an organization.',
  `name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Name describing the place. If not set by user it gets automatically filled.',
  `organizationId` bigint NOT NULL COMMENT 'Unique identifier of the organization the place is part of.',
  `trackingArea` json NOT NULL COMMENT 'rea subjected to movement tracking of people. It is a collection of (longitude, latitude) pairs consisting in a polygon. The string is expressed in JSON format.     '
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Area of an organization subjected to tracking.';

CREATE TABLE `PlaceAccess` (
  `id` bigint NOT NULL,
  `entranceTimestamp` datetime NOT NULL COMMENT 'Date and time of the moment in which the user entered the place.',
  `exitTimestamp` datetime DEFAULT NULL COMMENT 'Date and time of the moment in which the user left the place.',
  `exitToken` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Token generated by the server required for registering the user exit movement.',
  `placeId` bigint NOT NULL COMMENT 'Unique identifier of the place in which the user had access.',
  `orgAuthServerId` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'User unique identifier from the authentication server of the organization.'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Access to a place of an organization.';


ALTER TABLE `Favorite`
  ADD PRIMARY KEY (`userId`,`organizationId`),
  ADD KEY `organizationId` (`organizationId`);

ALTER TABLE `Organization`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `OrganizationAccess`
  ADD PRIMARY KEY (`id`),
  ADD KEY `organizationId` (`organizationId`);

ALTER TABLE `Permission`
  ADD PRIMARY KEY (`administratorId`,`organizationId`),
  ADD KEY `organizationId` (`organizationId`);

ALTER TABLE `Place`
  ADD PRIMARY KEY (`id`),
  ADD KEY `organizationId` (`organizationId`);

ALTER TABLE `PlaceAccess`
  ADD PRIMARY KEY (`id`),
  ADD KEY `placeId` (`placeId`);


ALTER TABLE `Organization`
  MODIFY `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'Unique identifier for an organization.';

ALTER TABLE `OrganizationAccess`
  MODIFY `id` bigint NOT NULL AUTO_INCREMENT;

ALTER TABLE `Place`
  MODIFY `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'Unique identifier for a place of an organization.';

ALTER TABLE `PlaceAccess`
  MODIFY `id` bigint NOT NULL AUTO_INCREMENT;


ALTER TABLE `Favorite`
  ADD CONSTRAINT `Favorite_ibfk_1` FOREIGN KEY (`organizationId`) REFERENCES `Organization` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `OrganizationAccess`
  ADD CONSTRAINT `OrganizationAccess_ibfk_1` FOREIGN KEY (`organizationId`) REFERENCES `Organization` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `Permission`
  ADD CONSTRAINT `Permission_ibfk_1` FOREIGN KEY (`organizationId`) REFERENCES `Organization` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `Place`
  ADD CONSTRAINT `Place_ibfk_1` FOREIGN KEY (`organizationId`) REFERENCES `Organization` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `PlaceAccess`
  ADD CONSTRAINT `PlaceAccess_ibfk_1` FOREIGN KEY (`placeId`) REFERENCES `Place` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
